package com.honeywell.hch.airtouchv2;

import com.honeywell.hch.airtouchv2.lib.util.DownloadUtils;
import com.honeywell.hch.airtouchv2.lib.util.JSONSerializer.JSONSerializeAnnotation;
import com.honeywell.hch.airtouchv2.lib.util.StringUtil;

import java.io.Serializable;

public class VersionCollector implements Serializable {

	private static final long serialVersionUID = 5997252056146210690L;
	
	@JSONSerializeAnnotation(actualClass = String.class)
	public String version_name = null;
	@JSONSerializeAnnotation(actualClass = Integer.class)
	public int version_code = 0;
	@JSONSerializeAnnotation(actualClass = String.class)
	public String updated = null;
	@JSONSerializeAnnotation(actualClass = Integer.class)
	public int size = 0; // default 0k
	@JSONSerializeAnnotation(actualClass = String.class)
	public String description = null;
	@JSONSerializeAnnotation(actualClass = String.class)
	public String download = null;
	
	// Generated by DownloadManager
	private long downloadId;
	
	public VersionCollector()
	{
		downloadId = DownloadUtils.FILE_DOWNLOAD_ID_INVALID;
	}
	
	public VersionCollector(String versionData)
	{
		fromString(versionData);
	}
	
	public long getDownloadId() {
		return downloadId;
	}

	public void setDownloadId(long downloadId) {
		this.downloadId = downloadId;
	}
	
	public void fromString(String sStr) {
		version_name = StringUtil.getParseValue(sStr, "version_name", "");
		version_code =  StringUtil.getParseValue(sStr, "version_code", 0);
		updated = StringUtil.getParseValue(sStr, "updated", "");
		size =  StringUtil.getParseValue(sStr, "size", 0);
		description = StringUtil.getParseValue(sStr, "description", "");
		download =  StringUtil.getParseValue(sStr, "download", "");
		downloadId =  StringUtil.getParseValue(sStr, "downloadId", DownloadUtils.FILE_DOWNLOAD_ID_INVALID);
	}

	@Override
	public String toString() {
		StringBuffer strBuffer = new StringBuffer();
		strBuffer.append("version_name=");
		strBuffer.append(version_name);
		strBuffer.append(";version_code=");
		strBuffer.append(version_code);
		strBuffer.append(";updated=");
		strBuffer.append(updated);
		strBuffer.append(";size=");
		strBuffer.append(size);
		strBuffer.append(";description=");
		strBuffer.append(description);
		strBuffer.append(";download=");
		strBuffer.append(download);
		strBuffer.append(";downloadId=");
		strBuffer.append(downloadId);
		return strBuffer.toString();
	}
}
